m11:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m11
    joint_speed: 1.0
    motor:
        id: 11
        init: 478
        min: 392
        max: 701

m12:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m12
    joint_speed: 1.0
    motor:
        id: 12
        init: 512
        min: 176
        max: 839

m13:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m13
    joint_speed: 1.0
    motor:
        id: 13
        init: 512
        min: 53
        max: 971

m21:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m21
    joint_speed: 1.0
    motor:
        id: 21
        init: 581
        min: 338
        max: 678

m22:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m22
    joint_speed: 1.0
    motor:
        id: 22
        init: 512
        min: 176
        max: 839

m23:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m23
    joint_speed: 1.0
    motor:
        id: 23
        init: 512
        min: 53
        max: 971

m31:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m31
    joint_speed: 1.0
    motor:
        id: 31
        init: 512
        min: 338
        max: 678

m32:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m32
    joint_speed: 1.0
    motor:
        id: 32
        init: 512
        min: 176
        max: 839

m33:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m33
    joint_speed: 1.0
    motor:
        id: 33
        init: 512
        min: 53
        max: 971

m41:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m41
    joint_speed: 1.0
    motor:
        id: 41
        init: 512
        min: 338
        max: 678

m42:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m42
    joint_speed: 1.0
    motor:
        id: 42
        init: 512
        min: 176
        max: 839

m43:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m43
    joint_speed: 1.0
    motor:
        id: 43
        init: 512
        min: 53
        max: 971

m51:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m51
    joint_speed: 1.0
    motor:
        id: 51
        init: 580
        min: 338
        max: 682

m52:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m52
    joint_speed: 1.0
    motor:
        id: 52
        init: 512
        min: 176
        max: 839

m53:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m53
    joint_speed: 1.0
    motor:
        id: 53
        init: 512
        min: 53
        max: 971

m61:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m61
    joint_speed: 1.0
    motor:
        id: 61
        init: 411
        min: 334
        max: 665

m62:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m62
    joint_speed: 1.0
    motor:
        id: 62
        init: 512
        min: 150
        max: 839

m63:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: m63
    joint_speed: 1.0
    motor:
        id: 63
        init: 512
        min: 53
        max: 971

